function circuitPanel = createDiagram(fig) 
    close all;
    circuitPanel = uipanel(fig,'Units','Pixels',"Position",[0 0 360 300]);
    %linkdata on;
    global circuitDiagram; circuitDiagram = struct();
    circuitDiagram.DAC1 = annotation(circuitPanel,"textbox",'Units','Pixels','Position',[30 55 50 30], ...
        "HorizontalAlignment","center","VerticalAlignment","middle", ...
        'String',"-","FontSize",8);
    circuitDiagram.L0 = annotation(circuitPanel,"Line",'Units','Pixels','Position',[80 70 30 0]);
    circuitDiagram.RB1branch.W0 = annotation(circuitPanel,"Line",'Units','Pixels','Position',[110 70 0 -30]);
    circuitDiagram.RB0branch.W0 = annotation(circuitPanel,"Line",'Units','Pixels','Position',[110 70 0 30]);
    circuitDiagram.RB0branch.W1 = annotation(circuitPanel,"Line",'Units','Pixels','Position',[110 100 20 0]);
    circuitDiagram.RB1branch.W1 = annotation(circuitPanel,"Line",'Units','Pixels','Position',[110 40 20 0]);
    circuitDiagram.RB0branch.RB0 = annotation(circuitPanel,"textbox",'Units','Pixels', ...
        'Position',[130 92 40 16],'String','1k',"HorizontalAlignment","center","VerticalAlignment", ...
        "middle","FontSize",6);
    circuitDiagram.RB1branch.RB1 = annotation(circuitPanel,"textbox",'Units','Pixels', ...
        'Position',[130 32 40 16],'String','100',"HorizontalAlignment","center", ...
        "VerticalAlignment","middle","FontSize",6);
    circuitDiagram.RB0branch.W2 = annotation(circuitPanel,"Line",'Units','Pixels','Position',[170 100 20 0]);
    circuitDiagram.RB1branch.W2 = annotation(circuitPanel,"Line",'Units','Pixels','Position',[170 40 20 0]);
    circuitDiagram.RB0branch.W3 = annotation(circuitPanel,"Line",'Units','Pixels','Position',[190 100 0 -30]);
    circuitDiagram.RB1branch.W3 = annotation(circuitPanel,"Line",'Units','Pixels','Position',[190 40 0 30]);
    circuitDiagram.Ib = annotation(circuitPanel,"arrow",'Units','Pixels','Position',[205 75 30 0]);
    circuitDiagram.L5 = annotation(circuitPanel,"Line",'Units','Pixels','Position',[190 70 50 0]);
    circuitDiagram.DUT = annotation(circuitPanel,"ellipse",'Units','Pixels','Position',[240 50 40 40]);
    circuitDiagram.textDUT = annotation(circuitPanel,"textbox",'Units','Pixels','Position',[240 50 40 40], ...
        "String","DUT","HorizontalAlignment","center","VerticalAlignment","middle",...
        "EdgeColor",'none');
    circuitDiagram.L6 = annotation(circuitPanel,"Line",'Units','Pixels','Position',[260 50 0 -20]);
    circuitDiagram.L7 = annotation(circuitPanel,"Line",'Units','Pixels','Position',[250 30 20 0]);
    circuitDiagram.L8 = annotation(circuitPanel,"Line",'Units','Pixels','Position',[255 25 10 0]);
    circuitDiagram.C0 = annotation(circuitPanel,"ellipse",'Units','Pixels','Position',[259 20 2 2]);
    circuitDiagram.L9 = annotation(circuitPanel,"Line",'Units','Pixels','Position',[260 90 0 40]);
    circuitDiagram.Ic = annotation(circuitPanel,"arrow",'Units','Pixels','Position',[265 125 0 -30]);
    circuitDiagram.Ictext = annotation(circuitPanel,"textbox",'Units','Pixels','Position',[280 110 20 10] ...
        ,'String',"-","HorizontalAlignment","center","VerticalAlignment","middle","EdgeColor",'none', ...
        "FontSize",8);
    circuitDiagram.VcArrow = annotation(circuitPanel,"arrow",'Units','Pixels','Position',[294 94 -36 -4],'Color', ...
        'r','HeadStyle','ellipse','HeadLength',4,'HeadWidth',4,'LineStyle',':');
    circuitDiagram.Vctext = annotation(circuitPanel,"textbox",'Units','Pixels','Position',[304 94 20 10] ...
        ,'String',"-","HorizontalAlignment","center","VerticalAlignment","middle","EdgeColor",'none' ...
        ,'Color','r',"FontSize",8);
    circuitDiagram.RC1branch.W0 = annotation(circuitPanel,"Line",'Units','Pixels','Position',[260 130 0 30]);
    circuitDiagram.RC2branch.W1 = annotation(circuitPanel,"Line",'Units','Pixels','Position',[260 130 60 0]);
    circuitDiagram.RC0branch.W1 = annotation(circuitPanel,"Line",'Units','Pixels','Position',[260 130 -60 0]);
    circuitDiagram.RC2branch.W0 = annotation(circuitPanel,"Line",'Units','Pixels','Position',[320 130 0 30]);
    circuitDiagram.RC0branch.W0 = annotation(circuitPanel,"Line",'Units','Pixels','Position',[200 130 0 30]);
    circuitDiagram.RC0branch.RC0 = annotation(circuitPanel,"textbox",'Units','Pixels', ...
        'Position',[192 160 16 40],'String','1K',"HorizontalAlignment","center", ...
        "VerticalAlignment","middle","FontSize",6);
    circuitDiagram.RC1branch.RC1 = annotation(circuitPanel,"textbox",'Units','Pixels', ...
        'Position',[252 160 16 40],'String','100',"HorizontalAlignment","center", ...
        "VerticalAlignment","middle","FontSize",6);
    circuitDiagram.RC2branch.RC2 = annotation(circuitPanel,"textbox",'Units','Pixels', ...
        'Position',[312 160 16 40],'String','10',"HorizontalAlignment","center", ...
        "VerticalAlignment","middle","FontSize",6);
    circuitDiagram.RC2branch.W2 = annotation(circuitPanel,"Line",'Units','Pixels','Position',[320 200 0 30]);
    circuitDiagram.RC1branch.W2 = annotation(circuitPanel,"Line",'Units','Pixels','Position',[260 200 0 30]);
    circuitDiagram.RC0branch.W2 = annotation(circuitPanel,"Line",'Units','Pixels','Position',[200 200 0 30]);
    circuitDiagram.RC0branch.W3 = annotation(circuitPanel,"Line",'Units','Pixels','Position',[260 230 -60 0]);
    circuitDiagram.RC2branch.W3 = annotation(circuitPanel,"Line",'Units','Pixels','Position',[260 230 60 0]);
    circuitDiagram.L16 = annotation(circuitPanel,"Line",'Units','Pixels','Position',[260 230 0 30]);
    circuitDiagram.L17 = annotation(circuitPanel,"Line",'Units','Pixels','Position',[260 260 -50 0]);
    circuitDiagram.DAC0 = annotation(circuitPanel,"textbox",'Units','Pixels','Position',[210 275 -50 -30], ...
        "HorizontalAlignment","center","VerticalAlignment","middle", ...
        'String',"-","FontSize",8);
    circuitDiagram.Ibtext = annotation(circuitPanel,"textbox",'Units','Pixels','Position',[210 80 20 10] ...
        ,'String',"-","HorizontalAlignment","center","VerticalAlignment","middle","EdgeColor",'none' ...
        ,"FontSize",8);
    circuitDiagram.VbArrow = annotation(circuitPanel,"arrow",'Units','Pixels', ...
        'Position',[230 50 9 21],'Color','r','HeadStyle','ellipse','HeadLength',4, ...
        'HeadWidth',4,'LineStyle',':');
    circuitDiagram.Vbtext = annotation(circuitPanel,"textbox",'Units','Pixels','Position',[220 40 20 10] ...
        ,'String',"-","HorizontalAlignment","center","VerticalAlignment","middle","EdgeColor",'none' ...
        ,'Color','r',"FontSize",8);
    circuitDiagram.RCnum = -1;
    circuitDiagram.RBnum = -1;
    circuitDiagram.IbArrowDirection = 1;
end
